[build]
builder = "nixpacks"
buildCommand = """
  cd backend && \
  /usr/local/bin/python -m pip install --upgrade pip && \
  /usr/local/bin/python -m pip install -r requirements.txt && \
  /usr/local/bin/python manage.py collectstatic --noinput
"""

[deploy]
startCommand = "cd backend && gunicorn config.wsgi"
healthcheckPath = "/"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = [
  "python39-full",
  "postgresql"
]

[service]
rootDirectory = "." 