[build]
builder = "nixpacks"

[deploy]
startCommand = "sh start.sh"
healthcheckPath = "/health/"
healthcheckTimeout = 60
restartPolicy = "on-failure"
healthcheckInterval = "10s"
healthcheckRetries = 3

[env]
PORT = "8000"
DJANGO_SETTINGS_MODULE = "config.settings_prod"
DATABASE_URL = "${DATABASE_URL}"
PGPORT = "5432"

[phases.setup]
nixPkgs = [
  "python39-full",
  "postgresql"
]

[[services]]
name = "web"
template = "dockerfile"

[[services.connects]]
name = "postgres"

[service]
rootDirectory = "."
startCommand = "gunicorn config.wsgi:application --bind 0.0.0.0:${PORT} --log-level debug --timeout 30 --workers 1 --threads 2" 