[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
PORT = "8000"

[phases.setup]
nixPkgs = [
  "python39-full",
  "postgresql"
]

[service]
rootDirectory = "." 