[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
healthcheckPath = "/"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = [
  "python39-full",
  "postgresql"
]

[service]
rootDirectory = "." 