[build]
builder = "nixpacks"
buildCommand = "python -m pip install --upgrade pip && pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn config.wsgi"
healthcheckPath = "/"
healthcheckTimeout = 100

[service]
rootDirectory = "backend" 