[build]
builder = "nixpacks"
buildCommand = """
  python3 -m venv venv
  source venv/bin/activate
  pip install --upgrade pip
  pip install -r requirements.txt
"""

[deploy]
startCommand = "gunicorn config.wsgi"
healthcheckPath = "/"
healthcheckTimeout = 100

[service]
rootDirectory = "backend"

[phases.setup]
nixPkgs = ["python39"] 