[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 60

[env]
PORT = "8000"

[phases.setup]
nixPkgs = [
  "python39-full",
  "postgresql"
]

[service]
rootDirectory = "." 