[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn config.wsgi:application --bind 0.0.0.0:${PORT:-8000} --log-level debug --timeout 30 --workers 1 --threads 2"
healthcheckPath = "/health/"
healthcheckTimeout = 60
restartPolicy = "on-failure"
healthcheckInterval = "10s"
healthcheckRetries = 3

[env]
DJANGO_SETTINGS_MODULE = "config.settings_prod"
DATABASE_URL = "${DATABASE_URL}"
PORT = "8000"

[phases.setup]
nixPkgs = [
  "python39-full",
  "postgresql"
]

[[services]]
name = "web"
template = "dockerfile"

[[services.connects]]
name = "postgres" 