[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "8000"
DJANGO_SETTINGS_MODULE = "config.settings_prod"
DATABASE_URL = "${DATABASE_URL}"
PGPORT = "5432"

[phases.setup]
nixPkgs = [
  "python39-full",
  "postgresql"
]

[service]
rootDirectory = "."
startCommand = "gunicorn config.wsgi:application --bind 0.0.0.0:${PORT} --log-level debug --timeout 30 --workers 1 --threads 2" 