[build]
builder = "nixpacks"
buildCommand = """
  cd backend && \
  python -m pip install --upgrade pip && \
  python -m pip install -r requirements.txt && \
  python manage.py collectstatic --noinput
"""

[deploy]
startCommand = "cd backend && gunicorn --chdir backend config.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["python", "python3", "python39", "python39Packages.pip", "postgresql"]

[service]
rootDirectory = "." 