# Generated by Django 5.1.3 on 2025-01-21 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="community",
            options={"verbose_name_plural": "Communities"},
        ),
        migrations.AlterModelOptions(
            name="resource",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="resourcecategory",
            options={
                "ordering": ["created_at"],
                "verbose_name_plural": "Resource Categories",
            },
        ),
        migrations.RemoveField(
            model_name="community",
            name="banner_image",
        ),
        migrations.RemoveField(
            model_name="resourcecategory",
            name="type",
        ),
        migrations.AddField(
            model_name="community",
            name="members",
            field=models.ManyToManyField(
                related_name="communities", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="resourcecategory",
            name="category_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MOVIES", "Movies"),
                    ("BOOKS", "Books"),
                    ("VIDEOS", "Videos"),
                    ("MUSIC", "Music"),
                    ("TUTORIALS", "Tutorials"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(upload_to="gallery/"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterModelTable(
            name="resource",
            table=None,
        ),
    ]
