# Generated by Django 5.1.3 on 2025-01-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcecategory",
            name="preview_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_previews/"
            ),
        ),
    ]
