# Generated by Django 5.1.3 on 2025-01-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_community_options_alter_resource_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="banner_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="community_banners/"
            ),
        ),
    ]
