# Generated by Django 5.1.3 on 2025-01-21 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_add_resource_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resourcecategory",
            options={},
        ),
        migrations.RemoveField(
            model_name="resource",
            name="content",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="file",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="resource_type",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="resource",
            name="author",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resourcecategory",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resourcecategory",
            unique_together={("community", "category_type")},
        ),
        migrations.AlterModelTable(
            name="resource",
            table="main_resource",
        ),
    ]
