# Generated by Django 5.1.3 on 2025-01-24 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_category_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resourcecategory",
            options={},
        ),
    ]
