# Generated by Django 5.1.3 on 2025-01-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_resourcecategory_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="author",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="description",
        ),
        migrations.AddField(
            model_name="resource",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
