# Generated by Django 5.1.3 on 2025-01-27 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="resource",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.resourcecategory"
            ),
        ),
    ]
