# Generated by Django 5.1.3 on 2025-01-27 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_resource_views_alter_resource_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcecategory",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="resourcecategory",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.community"
            ),
        ),
        migrations.AlterField(
            model_name="resourcecategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resourcecategory",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
