# Generated by Django 5.1.3 on 2025-01-28 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_update_forumpost_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forumpost",
            name="updated_at",
        ),
    ]
