# Generated by Django 5.1.3 on 2025-01-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_forumpost_content_reaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("like", "👍"),
                    ("heart", "❤️"),
                    ("funny", "😂"),
                    ("wow", "😮"),
                    ("sad", "😢"),
                    ("angry", "😠"),
                ],
                max_length=10,
            ),
        ),
    ]
