# Generated by Django 5.1.3 on 2025-01-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_poll_polloption_pollvote_polloption_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="question",
            field=models.TextField(),
        ),
    ]
