# Generated by Django 5.1.3 on 2025-01-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_recommendedproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendedproduct",
            name="url",
            field=models.URLField(max_length=2000),
        ),
    ]
