# Generated by Django 5.1.3 on 2025-01-30 00:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_savedimage_savedproduct_savedresource"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="savedproduct",
            options={"ordering": ["-saved_at"]},
        ),
    ]
